executors:
  go:
    working_directory: ~/go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/go:1.11.5
  docker-builder:
    working_directory: ~/go/src/github.com/hashicorp/nomad
    machine: true # TODO: Find latest docker image id

jobs:
  build-deps-image:
    executor: docker-builder
    steps:
      - checkout
      - run: docker pull dantoml/nomad-build-image:$CIRCLE_SHA1 || true
      - run: docker build -t dantoml/nomad-build-image:$CIRCLE_SHA1 ./.circleci/build-images/go
      - run: docker push dantoml/nomad-build-image:$CIRCLE_SHA1

  build-release:
    executor: go
    steps:
      - checkout
      - run: make bootstrap
      - run: make prerelease
      - run: git status
      - run: make release

  build-website:
    # setting the working_directory along with the checkout path allows us to not have
    # to cd into the website/ directory for commands
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      # restores gem cache
      - restore_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: install gems
          command: bundle check || bundle install --path vendor/bundle --retry=3

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle

      - run:
          name: middleman build
          command: bundle exec middleman build

      - run:
          name: website deploy
          command: ./scripts/deploy.sh

workflows:
  website:
    jobs:
      - build-ci-images:
          context: dani-test-context
          filters:
            branches:
              only: dani/circleci
      - build-website:
          context: static-sites
          filters:
            branches:
              only: stable-website
